### ISSUE TITLE
WinHttpException when running in azure Websites + CoreCLR

### ISSUE THREAD

**Issue by sandorfr** [aspnet/HttpClient#16]
Looks like there is something wrong with proxy detection. When trying to make call in azure web site environment it throws a WinHttpException.

WinHttpException: An attempt was made to access a socket in a way forbidden by its access permissions.
   System.Net.Http.WinInetProxyHelper.GetProxyForUrl(SafeInternetHandle sessionHandle, Uri uri, WINHTTP_PROXY_INFO& proxyInfo)

As a workaround it is possible to pass a handler with UseProxy set to false :
```csharp
using (HttpClient client = new HttpClient(new HttpClientHandler() { UseProxy = false })) {

}
```

Maybe this behavior is intended but it should throw with a more explicit message such as "Proxy not supported in your current environment" or something like that.

There is [a thread](http://forums.asp.net/p/2032028/5856908.aspx?p=True&t=635587372113984245) about this issue on aspnet vnext forums

**Comment by Tratcher** [comment]
This is not the HttpClient implementation you are looking for, it has no proxy detection. The implementation you are using is not yet on github so please open this bug on https://connect.microsoft.com/ instead.

**Comment by sandorfr** [comment]
So basically the aspnet version shipped with latest VS preview is still wired to the old httpclient but with future releases it will be replaced by this implementation. So this is just a temporary issue?
