### ISSUE TITLE
GET, PUT, DELETE, HEAD, POST support in cross platform

### ISSUE THREAD

**Issue by damienbod** [aspnet/HttpClient#17]
As a developer I would like to use the HttpClient in a cross platform environment with support for GET, PUT, DELETE, HEAD, POST and also use the Response status codes without dependencies on .NET 4.5 or lower.

Is/Will this be possible or could I extend the HttpClient for this? What's the roadmap, or what are your views?

greetings Damien

**Comment by Tratcher** [comment]
Ok, if you don't want .NET 4.0/4.5 (or aspnet50) are you targeting Core CLR instead (aspnetcore50)?

**Comment by damienbod** [comment]
I want to create a library (nuget package) with can be used by any other aspnet50 which runs on any hosting environment. Is this possible, when I use .NET 4.0/4.5 assembly dependencies? It's not so clear for me,  when/if I should target aspnet50 and/or aspnetcore50. 

Greetings Damien

**Comment by Eilon** [comment]
The HttpClient library built here is actually a temporary private implementation that's used only in the `kpm` command. This library isn't published as a NuGet package anywhere. I think the plan is for this repo to eventually be deleted.

To make web requests you can use `System.Net.HttpClient` that does ship. I believe that works in CoreCLR (Windows), .NET 4.x (Windows), and on Mono.

**Comment by damienbod** [comment]
Thanks

I can get my library working for aspnet50 using 
"aspnet50": {
			"dependencies": {
				"Newtonsoft.Json": "6.0.8.0",
				"Microsoft.Net.Http": "2.2.7-beta"
			}
		},
What about aspnetcore50?

https://github.com/damienbod/ElasticsearchCRUD/blob/aspnet5/ElasticsearchCRUD.vNext/ElasticsearchCRUD/project.json

It's not so easy to find out which package to use and which not, is their any strategy or docs I could use to help with this?

Greetings Damien

**Comment by Eilon** [comment]
You can use http://packagesearch.azurewebsites.net/ to locate a type or method and see what package it's in.

**Comment by damienbod** [comment]
Thanks a lot.

Will aspnetcore50 support Microsoft.Net.Http in the future or do I need to implement a different version for aspnetcore50?

Greetings Damien

**Comment by Eilon** [comment]
It will absolutely be supported on aspnetcore50 in the future! My team (ASP.NET) is working closely with the networking team (they write HttpClient, among other things) to get this working across all the supported environments.

**Comment by damienbod** [comment]
Hi Eilon

Thanks for your reply. That's great news.

greetings Damien

**Comment by adamhathcock** [comment]
Hi all,

I'm just wondering if there's an ETA for this.  It will be done for release or do contributions need to be made?

Thanks!

**Comment by Tratcher** [comment]
@adamhathcock This repo contains only temporary code and is unlikely to add additional functionality. We're waiting for a full implementation to become available in https://github.com/dotnet. There is already support available for net45/dnx45 on Windows and Mono. There is also dnxcore50 support available on Windows. The remaining gap is dnxcore50 on Linix/Mac.

**Comment by adamhathcock** [comment]
Thanks for the reply @Tratcher 

I was aware of the WinHttpHandler for Windows/Mono.  I was thinking that this was supposed to be the "official" implementation of a Handler for HttpClient that would be cross-platform for dnxcore50.  I guess that's going into the core class library?

**Comment by Tratcher** [comment]
Right, the official implementation will be in in https://github.com/dotnet. We're not sure what the final form will be though.

**Comment by muratg** [comment]
We have finally moved to the official HttpClient.
