### ISSUE TITLE
RegisterPrefix support in HttpClient

### ISSUE THREAD

**Issue by govin** [aspnet/HttpClient#24]
The WebRequest class in C# has a RegisterPrefix method which lets you register handlers for serving various protocols. - https://msdn.microsoft.com/en-us/library/system.net.webrequest.registerprefix%28v=vs.110%29.aspx

RestSharp (3rd party library) uses WebRequest class underneath and hence gets this feature automatically. But it looks like HttpClient does not use WebRequest class underneath? It will be nice to build this feature into the HttpClient class itself - we have use cases where we use custom prefixes such as svc:// which are mapped to http:// counterparts based on some lookups.

**Comment by Tratcher** [comment]
FYI, this is not the primary repo for System.Net.Http.HttpClient, we only implement ManagedHandler here. The primary repo is not publicly available yet.

WebRequest was designed to give you a consistent API across a variety of protocols. There is built in support for HTTP, FTP, and FILE, and you could add others.  HttpClient is only designed to work with HTTP so it doesn't use the same RegisterPrefix extensibility.  The implementation in this repo (ManagedHandler) doesn't use WebReqeuest at all, it directly uses Sockets.

Are you trying to use svc:// uris to access HTTP resources? HttpRequestMessage requires URIs use the http or https schemes.

**Comment by Tratcher** [comment]
The actual HttpClient code is here:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/HttpClient.cs
